### PR TITLE
Avoid having implicit imports.

### PR DESCRIPTION
**Pull request by jd-foster**
Changes `using` to ~~`import`~~ explicit formula of`using Package: Package` for dependent packages.
~~Possibly addresses #22~~

### CODE REVIEW

**Comment by jecs** [comment]
May I ask why CI tests Julia 1.6? I believe that 1.10 is the new LTS version.

I wonder if the failing CI is related at all to #22.

**Comment by jd-foster** [comment]
Even without issue 22, I think the Julia community is heading towards this style anyway.

**Comment by BeastyBlacksmith** [comment]
To clarify: both `using JSON: JSON` and `import JSON` only bring `JSON` into namespace. The only difference is that `import` allows methods from `JSON` being extended without qualification while `using JSON: JSON` does not (AFAIK).

**Comment by jd-foster** [comment]
Right, from here: https://docs.julialang.org/en/v1/manual/modules/#using-and-import-with-specific-identifiers,-and-adding-methods

**Comment by jd-foster** [comment]
Changed to the `using X: X` form for Base64 and Kaleido_jll

**Pull request merged**
